// 処理系のテスト４４
// 異常ケース３３: 関数内のreturn文に返り値がない

int move(int x);

int move(int x)
{
  int op = 1000;
  return;	// 関数 move() の return に返り値がないのでエラー
}

void main()
{
  move(10);
}

